### ISSUE TITLE
Remove `canvas` default export from `canvas-kit-react/tokens` package

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#1021]
## 💡 Suggestion

We should remove the `canvas` default export from `canvas-kit-react/tokens` package. It should instead be a named export or removed entirely. This would also involve a codemod to help consumers migrate away from its use.

## Motivation

- We're moving away from default exports in CK
-  It would allow us to clean up our tokens and how we provide them.

**Comment by myvuuu** [comment]
Impact to consumers:

Consumers use several tokens at once through Canvas. Instead of importing tokens through Canvas, they will need to import the tokens directly AND create a local name for the tokens that they're importing if there is a conflict (ex: if a team has another variable named 'colors' and our tokens are named 'colors' already, it would result in a conflict that can be resolved)

@alanbsmith will check in on how many teams will be impacted by this (that the code mod cannot handle)

**Comment by alanbsmith** [comment]
This was resolved with #1634
