### ISSUE TITLE
`Popup.Popper` doesn't allow for attributes to be added to the `Popper` element in the dom

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#1137]
## 🐛 Bug Report

In v4 I was able to pass data test ids to the `Popper` component. In v5, I'm able to add those attributes but they do not reflect in the dom element.

## To Reproduce

https://codesandbox.io/s/upbeat-dream-fh28g?file=/src/App.tsx

Notice when I add `data-testid="foo-bar"` to the Popper compnent, that attribute is not present in the dom when you inspect it.

## Expected Behavior

I should be able to pass data test ids and attributes to the Popper component, instead the attributes never get added to the underlying dom element.

**Comment by NicholasBoll** [comment]
## Problem
`Popper` is a weird component. It portals content to a non-semantic `div` element that is not controlled by React. The `div` is created by the `PopupStack`. The `ref` is forwarded to that `PopupStack` `div` element, but spreading props would be difficult. Attributes could be easily spread, but things like `onClick` would be extremely difficult to pull off transparently.

This worked in v4 because an extra `div` was rendered. This meant that you had 2 `div` elements, one created by the `PopupStack` and one created by the `Popper` component.

In v5, we've been removing extra element wrappers because it complicates the following questions:
- What element should the `ref` point to?
- Where should extra props go?

If we represent components as close to 1:1 to an element, the answers are obvious: "the only element that is rendered".

This can be worked around in v5 by manually adding a `div` element with any props you'd like around the content inside `Popup.Popper`.

## Question
We have 3 options to proceed:
1. Add a non-semantic `div` to the `Popper` component to spread extra props to. The `ref` would not point to this element.
    - Pros:
        - spreading extra props works like other components
    - Cons:
        - `ref` is pointing to a different element
2. Leave the `Popper` component as is. If extra props are desired on some element, a `div` could be manually added:
    ```tsx
    <Popup.Popper>
      <div data-testid="foo-bar">Content</div>
    <Popup.Popper >
    ```
    - Pros:
        - No extra elements between
    - Cons:
        - Extra props don't spread like almost any other component
3. Manually spread extra props to the `div` element that React does not control.
    - Pros:
        - No extra elements and extra attributes mostly work as expected
    - Cons:
        - Wrought with edge cases
        - Callback handlers would need special treatment and wouldn't be real React synthetic events, unless we ignore entirely
        - Extra props would be treated always like properties instead of attributes
        - `css` would not work at all

The question is, which of these options makes the most sense? No matter what, the `Popper` component should be documented to cover any deviation from other components.

**Comment by mannycarrera4** [comment]
Option 2 is the way I've moved forward and it. has worked just fine or adding any attributes to `Popup.Body`
