### ISSUE TITLE
When extending component props for an interface, the consumer has to redefine the props based on the element.

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#1145]
## 🐛 Bug Report

In `v4`  as a consumer I could extend a component props and add on to it.

```tsx
   import {TextInputProps} from '@workday/canvas-kit-react-text-input'
   export interface MyComponentProps extends TextInputProps {
      myExtraProp: boolean
   }
```

Where TextInputProps has attributes like `placeholder` and `disabled`

In `v5` this is not possible and we have to redefine those props. I believe `createComponent` handle adding those attributes based on the element when it uses the `as` prop however, as a consumer we lose all those props and have to redefine them.

When I try something like this:

```tsx
   import {TextInputProps} from '@workday/canvas-kit-react-text-input'
   export interface MyComponentProps extends TextInputProps {
      myExtraProp: boolean
   }
```

`MyComponent` doesn't have access to the base props for TextInput like disabled or placeholder

It would be great to have those props exported someone instead of redefining them

**Comment by NicholasBoll** [comment]
Since `TextInput` uses `createComponent` and `createComponent` has an `as` prop that could change the element rendered, the props don't contain any HTML attributes. Those attributes are determined at usage time, but it is quite common to extend existing components somehow. We've also started removing prop interfaces from exports.

`ExtractProps` was created to offset this, but only extracts explicit props defined by the component. I think we should extend `ExtractProps` to return the HTML attributes of a component with an optional element override in the case were `as` is used.
