### ISSUE TITLE
Box Component tosses out valid props when using 'as'

### ISSUE THREAD

**Issue by vibdev** [Workday/canvas-kit#1482]
## 🐛 Bug Report

Box and all its derivatives (Flex, Stack, etc) allow you to use 'as' to override the element. You can use 'as' to set it to render as a different React Component. The types for Box are correct and merge Box and the other Component props, but Box ends up eating any props that are not Box props or native HTML props.

This is because Box is defined as:
```jsx
const shouldForwardProp = (prop: string) => {
  return isPropValid(prop) && !omittedProps.includes(prop);
};

const StyledBox = styled('div', {shouldForwardProp})<StyledType & BoxProps>(...)
```

The `isPropValid` removes all the other valid props associated with the other React Component.

This could easily lead to runtime error that are hard to debug since Typescript has given the ok.

## To Reproduce

<Box as='AnyComponent' requiredProp='my value' />

## Expected Behavior

Box renders as AnyComponent and passes requiredProp.

## Actual Results

Box renders as AnyComponent but does not pass requiredProp.

## Link to repl or repo (highly encouraged)
https://codesandbox.io/s/box-prop-eating-qlrp8s

<img width="954" alt="Screen Shot 2022-02-17 at 3 44 06 PM" src="https://user-images.githubusercontent.com/1562615/154590309-0978a53a-cd41-4805-bcb4-126b3800a058.png">

**Comment by NicholasBoll** [comment]
Thanks for filing this with detail! I noticed this as well. `styled` is a weird API for this case. If you do not pass in a `shouldForwardProp`, `styled` will chose one based on the incoming tag. If the tag is a string (element), then `isValidProp` is automatically used. If the tag is a component, then `as` is stripped and the rest is left alone.

The problem is `shouldForwardProp` doesn't give you this information. The only argument you get in the function is the prop name. But how can you make a decision correctly without access to the tag being rendered?!

Something we thought of was to remove the custom `shouldForwardProp` from `StyledBox` and instead make a function call inside `Box` with the `Element` variable passed in so we can make a decision there based on the element requested.

**Comment by NicholasBoll** [comment]
Here's what I did for Modals in v7:

https://github.com/Workday/canvas-kit/pull/1259/files#diff-41757921f1e65aaeeb7d1c1d4a7735c74f8415466a5bb06c87372f92b8be78e7R79-R86

The change was to make 2 different styled components - one for elements and one for components and conditionally render based on if the tag is a string or a component.

**Comment by NicholasBoll** [comment]
@alanbsmith Should we backport the fix into v6?

**Comment by alanbsmith** [comment]
Yeah, let's fix it. 👍🏻
