### ISSUE TITLE
Dependency Upgrades for Canvas Site

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1553]
## 💡 Suggestion

Make the following dependency upgrades:
- [x] React 16.14 OR React 17.X
- [x] Emotion 11
- [x] Typescript 4.1 or higher
- [x] Update to the latest icons and graphics packages (4 total)
- [x] Canvas Kit v7

**Comment by jamesfan** [comment]
FYI: this is mostly done as of 5/6. The Canvas Site was upgraded to the latest versions of React 17, Emotion 11, and TypeScript 4.1. We also updated the following design asset packages to the latest versions:

- @workday/canvas-accent-icons-web@^3.0.0
- @workday/canvas-applet-icons-web@^2.0.0
- @workday/canvas-graphics-web@^4.0.0
- @workday/canvas-system-icons-web@^3.0.0

There's an issue where prop tables aren't rendering for `SystemIcon` or `AccentIcon` after performing the upgrades, but otherwise the site appears to work fine.

I'm leaving this issue open in the `ready for review` stage as we look into these minor issues and to continue monitoring the Canvas Site upgrade as more v7 PRs are merged on canvas-kit.
