### ISSUE TITLE
Spike for Managing Multiple Versions of Canvas Docs on the Canvas DS Site

### ISSUE THREAD

**Issue by myvuuu** [Workday/canvas-kit#1583]
## 🔍 Spike /  Exploration

A spike needs to be conducted to determine how multiple versions (based on CK major releases) of Canvas documentation can be presented to users on the Canvas DS site

## What questions would be answered once this spike was completed?

1. Can the website use a toggle or drop-down for users to select a CK major version and filter the website based off of their selection?
2. Can multiple storybook versions of CK docs be imported into the site?
4. If a user selects v6 as their CK version (from a toggle or drop-down), can the Side Panel doc (usage guidance, CK docs, etc.) be filtered to show the last version of that page from the last site release prior to the v7 release?

## Other Success Criteria?

1. Spike results are documented and discussed with the team

**Comment by mannycarrera4** [comment]
Did some digging on this with @jamesfan!
I think the approach we're thinking of involves just changing the version of the canvas site it self.

- Trying to import specific versions of mdx files based on the version selected by the user seems quite difficult to manage
- If we look at how other design systems approach this, they just change the version of their site. This approach will probably work best since the canvas site is typically in alignment with the latest major version of canvas kit. Look at [Chakra](https://chakra-ui.com/) for example as well as [Uber](https://baseweb.design/). Notice that the URL changes with the version
- I think the approach that makes the most sense is to have different builds of the site with the different versions that we support, in this case we can always showcase our support branch and our current major version.

### Questions?
- How many versions do we want to showcase?

### Effort

- In terms of changes on the cavas kit site, I don't think we have to change much. 
- We probably need to talk to @d-bye regarding how to host different versions

**Comment by myvuuu** [comment]
Spike has been completed
