### ISSUE TITLE
Spike: Cypress-storybook support for React 18

### ISSUE THREAD

**Issue by NicholasBoll** [Workday/canvas-kit#1667]
## 🔍 Spike /  Exploration

The https://github.com/NicholasBoll/cypress-storybook plugin doesn't currently support React 18 with the change to `root.unmount()`. React <18 uses `ReactDOM.unmountComponentAtNode()` which is used by `cypress-storybook` to force a refresh of the story for performance. React 18 introduced the concept of [render roots](https://reactjs.org/docs/react-dom-client.html#createroot):

```js
const container = document.getElementById('root');

// React <18
ReactDOM.render(<div />, container);

// unmount
ReactDOM.unmountComponentAtNode(container);

// React 18
const root = ReactDOM.createRoot(container);

// unmount
root.unmount();
```

This means, without access to the `root` variable, `cypress-storybook` can no longer unmount.

## What questions would be answered once this spike was completed?

1. Can `cypress-storybook` use a different way to force rerendering of a story?
2. If not, how difficult is it to convert to using the [Cypress Component runner](https://www.cypress.io/blog/2021/04/06/introducing-the-cypress-component-test-runner/)?

## Does this relate to any existing issues?

#1655

**Comment by mannycarrera4** [comment]
Still investigating but I also saw this: https://www.cypress.io/blog/2021/05/19/cypress-x-storybook-2-0/

**Comment by mannycarrera4** [comment]
I was also looking at this: https://dev.to/mbarzeev/integrating-storybook-with-cypress-and-hmr-4082

**Comment by RayRedGoose** [comment]
Storybook 6.5 upgrade caused CI failure because story is not reloaded after the previous test. 
1. `cypress-storybook` has opened [issue for this](https://github.com/NicholasBoll/cypress-storybook/issues/53). But as temporary solution we added other story load with wait time before tested to force reload tested story. 
2. It seems like we can't fully rely on Storybook for testing. So it's reasonable to switch cypress+storybook testing to cypress component testing to get more control over testing render. 

It's also covered in [React 18 discussion](https://github.com/Workday/canvas-kit/discussions/1545)

**Comment by RayRedGoose** [comment]
[Result of Spike](https://github.com/Workday/canvas-kit/issues/1690)

**Comment by cmelion** [comment]
> I was also looking at this: https://dev.to/mbarzeev/integrating-storybook-with-cypress-and-hmr-4082

Has anyone tried this approach with React 18?
