### ISSUE TITLE
PaginationButton focus should be themable 

### ISSUE THREAD

**Issue by mannycarrera4** [Workday/canvas-kit#2940]
## 🐛 Bug Report

Currently, the canvas provider theme does not theme pagination button correctly. Here's a [sandbox](https://stackblitz.com/edit/select-branded-fnwmpa-a8a4du?file=src%2FApp.tsx) demonstrating the issue.

**Comment by NicholasBoll** [comment]
The `PaginationButton` focus is themable, but it themes based on primary brand color rather than the focus color.

https://github.com/Workday/canvas-kit/blob/0c48e7ee933834afbaeba97b007bba126e993318/modules/react/button/lib/BaseButton.tsx#L192

The brand color used here should be `brand.common.focusOutline` instead of `branch.primary.base`.
