### ISSUE TITLE
Skeleton: missing backgroundColor props for animated layer

### ISSUE THREAD

**Issue by 6r3al** [Workday/canvas-kit#451]
## 🚀 Feature Proposal

The Skeleton looks good when the elements underneath is white but it looks off on different colors.
Would be great for the Skeleton component to have a backgroundColor props so that the animated layer can intertwine better when over non-white elements. 

## Motivation

Better look and feel.

## Example

<img width="1034" alt="skeleton" src="https://user-images.githubusercontent.com/35978459/74030364-cbc05600-49a6-11ea-952c-03099c352682.png">

**Comment by NicholasBoll** [comment]
Hmm. I can change the colors of everything except for `SkeletonText`, which applies extra properties to the text container vs individual lines.

@anicholls @lychyi, should we use a color + alpha to get a similar effect against different background colors? Choosing a specific background color seems more difficult that it would have to be.

**Comment by NicholasBoll** [comment]
Here's a codesandbox of what you can do now: https://codesandbox.io/s/relaxed-boyd-d18il

**Comment by 6r3al** [comment]
Hi Nicholas, thanks for taking a look at this one and sending this codesandbox. 
Let me clarify my request.
What I find a bit off is that the animated layer is not only visible on the Skeleton elements but also when moving over the underneath component (arrows in the screenshot attached). 
Rather than having a big animated layer moving above the whole Skeleton block, we could maybe:
- animate each individual Skeleton element
- have a specific animated layer moving for each individual Skeleton element
Does it make more sense?

<img width="667" alt="Screenshot 2020-02-11 at 09 54 23" src="https://user-images.githubusercontent.com/35978459/74230768-f79c4e00-4cbc-11ea-9d88-5e8b491606aa.png">


<img width="667" alt="Screenshot 2020-02-11 at 09 54 23" src="https://user-images.githubusercontent.com/35978459/74227595-b5700e00-4cb6-11ea-89f4-eef59b43761f.png">

**Comment by NicholasBoll** [comment]
I also noticed the animation is not very efficient in terms of CPU. The `left` parameter is what is being animated rather than the `transform` property. This means that the loading animation will be choppy or pause if any other work is happening on the UI thread. Using the `transform` will allow the animation to happen even while the UI thread is busy. I was able to change the animation to use `translate: transformX()` instead of `left` and that improved the jank.

I think there is one larger animation to have some coordination between all the elements of a skeleton view. If they were individual, the animation wouldn't be coordinated.

There is probably a way to do it. Do you have time to try something out?

**Comment by anicholls** [comment]
Hey @NicholasBoll & @6r3al!

This is definitely something that's been discussed before. I think when the `Skeleton` component was being built, the author ran into issues trying to mask the animation to each individual element without having a separate animation for each (which we were trying to avoid for syncing and performance reasons). This solution was a "good enough for now" decision when it went in. I believe it was @Parker-Ledoux who worked on this, so maybe he could lend some info. 

@NicholasBoll I definitely agree we should be animating `transform`, not `left`. Not sure how this got that in without that. 

On a related note, we also have #134 which could be resolved at the same time. 

From a design perspective, there has been discussion about reconsidering this animation and using a simple pulsing fade between two colors instead of the sliding shimmer. If there's enough of a technical argument, it's definitely something we could take a closer look at changing. Though this would have a larger impact as the animation exists in places other than this repo.

**Comment by willklein** [comment]
This will be addressed with a different animation in #1001.
