### ISSUE TITLE
Add Box, Flex, and Stack

### ISSUE THREAD

**Issue by alanbsmith** [Workday/canvas-kit#771]
## 🚀 Feature Proposal

We should add spacing / layout components to canvas-kit. We can start with the following:

* Box - a low-level primitive component
* Flex - a low-level layout component for building layouts with Flexbox
* Stack / HStack / VStack - higher-level abstractions for building layouts with Flexbox

## Motivation

This is an important part of developing [a component hierarchy](https://medium.com/@_alanbsmith/understanding-component-hierarchy-d5ce153acab3) that will enable us to make canvas-kit more flexible and extensible.

Other links:

* [More reading on `Box`](https://www.notion.so/alanbsmith/Box-f80b8ac241bb41e0a3430d49a6f27d64)
* [More reading on `Flex`](https://www.notion.so/alanbsmith/Flex-5d9de801f6ca47eda68e55a378761e9c)

## Example

Here's a [proof of concept](https://codesandbox.io/s/stack-proof-of-concept-psdmd?file=/src/App.tsx) for `Box`, `Flex`, and `Stack`

**Comment by mathalete** [comment]
Hi @alanbsmith I get the truncation is an example - but note that the overflow:ellipsis pattern that uses the title attribute isn't accessible to touch, dictation or keyboard users.

I do think a primitive for headings would be helpful as reusable components will appear in different contexts, at different levels in the document heading structure. It should therefore be possible to change the heading level of the component’s main heading via a level primitive / prop.

The `aria-level` property/attribute can then be used to change the perceived level in assistive technologies. Note that `aria-level` only works on heading elements (`<h1>` — `<h6>`) or elements with `role="heading"`. It is recommended the default prop value is 2, since most components will start at that level.

```
<!-- component code -->
<h2 aria-level="{this.props.level}"></h2>

<!-- instance -->
<MyComponent level="3" />

<!-- how a screen reader perceives the MyComponent heading -->
<h3>Component name / main component heading text</h3>
```

**Comment by alanbsmith** [comment]
Thanks for the feedback, @mathalete! I made this issue as a quick note, but we should talk about it more. 😀 There are a lot of situations where truncation is being used (or will potentially be used), and I’d like to have a11y guarantees and guidelines all in one spot. That’ll make it easier for everyone to get it right on the first pass.
