### ISSUE TITLE
Labs menu component does not collapse around it's content below a minimum width

### ISSUE THREAD

**Issue by jhensley** [Workday/canvas-kit#859]
## 🐛 Bug Report

The `<Menu/>` component does not fully collapse down to it's contents as the `width` prop suggests when below a minimum width. 

From the `width` prop's documentation: The width of the Menu. If no value is provided, the Menu will collapse around its content.

However, further in the code, a `min-width` style rule is set on both the styled `<ul/>` and the generated `<Card/>` wrapper.

## To Reproduce

1. Create a menu with narrow contents, such as a list of single or double digit numbers.

## Expected Behavior

Expectation is that the menu collapse around the narrow contents plus the appropriate padding, etc.

## Actual Results

The width of the container has an inline style of `min-width: 102px;` and is not collapsing around the contents.

## Browser (if applicable)

All browsers.

## Link to repl or repo (highly encouraged)

https://repl.it/@jhensley1/JampackedMeaslyBellsandwhistles

### Error Output

<img width="120" alt="Screen Shot 2020-09-15 at 3 08 41 PM" src="https://user-images.githubusercontent.com/482316/93265124-5f3fdd80-f765-11ea-9ff3-f463f0986647.png">

**Comment by alanbsmith** [comment]
Labeling this as `blocked` until we get some more detail around how we want to handle this from design.

**Comment by alanbsmith** [comment]
I think there are two ways to solve this: We could get rid of the `minWidth` altogether, or we could add an optional `minWidth` prop that has a default of `100 + 2px` (the current value).

## Remove the `minWidth`

### Pros

* Supports more narrow menu without adding to Menu props
* Removes an obscure design decision from the component

### Cons

* Would change widths of existing narrow menus in product apps (Is this really a con though?)
* Might cause some teams to want a minWidth for their use case

## Add Optional `minWidth` Prop

### Pros

* Won't affect existing applications because of `100 + 2px` default
* Pretty straight-forward API for teams to modify minWidth in the Menu component

### Cons

* Keeps the obscure `100 + 2px` default around
* Adds yet another prop to the Menu component
* Could create inconsistency with teams choosing their own preferred minWidths instead of following defaults

**Comment by willklein** [comment]
I agree with @alanbsmith's first solution, removing `minWidth` altogether. I agree with there being an implicit behavior (`minWidth` being automatic), it should be the one documented, and that is consistent with the desired behavior @jhensley suggested.

Regarding the other idea proposed by @alanbsmith, adding an optional `minWidth` prop, I think the cons he named are significant enough to go with the other solution. I'd prefer not to have an extra prop, or allow inconsistencies to continue or spread throughout any application using Canvas Kit. I also considered other approaches like a `collapse` prop (boolean to indicate whether the current `minWidth` should apply) and it would suffer from the same cons.

This may be a visually breaking change for some applications but it should not negatively impact any user experience. I'll vet this with some other folks but I don't see a problem changing the default behavior to match our documentation.
