### ISSUE TITLE
Document theming for custom components

### ISSUE THREAD

**Issue by anicholls** [Workday/canvas-kit#864]
## 🚀 Feature Proposal

The helpful `useTheme()` hook and `styled` function are not documented here: https://github.com/Workday/canvas-kit/blob/master/modules/react/common/lib/theming/README.md

## Motivation

We should add documentation for building your own custom components using the custom theme so people know they can use it in their own components!

**Comment by RayRedGoose** [comment]
It's still an issue, and requires update documentation on theming.

It good to mention `styled` function, because it helps to automatically switch direction-sensitive styles for RTL and LTR directions). 
`useTheme` is used in one example (breakpoints) but no overview and  information about other functionality.

Also, storybook `theming` page is pretty empty, so we need to add all this info to storybook too.

**Comment by jaclynjessup** [comment]
#923

**Comment by myvuuu** [comment]
Closing this out since we'll be revisiting and documenting theming as part of the v10 work.
